version: 2
sources:
   - name: raw
     schema: flash-spot-462408-s5.gz_raw_data #où se situe la table dans BQ
     description: greenwez raw data source
     tables:
         - name: sales
           identifier: flash-spot-462408-s5.gz_raw_data.raw_sales #Quel est le nom exacte de la table dans BQ
           description: sales of greewneez / we have one row per product_id found in each order_id
           columns:
             - name: "(orders_id || '-' || pdt_id)"
               description: primary key of the table
               tests:
                 - unique
                 - not_null
         - name: product
           identifier: flash-spot-462408-s5.gz_raw_data.raw_product
           description: purchase_price by products_id
           columns:
             - name: products_id
               description: primary key of the table
               tests:
                 - unique
                 - not_null       
         - name: ship
           identifier : flash-spot-462408-s5.gz_raw_data.raw_ship
           description : shipping cost by orders_id
           columns :
             - name: orders_id
               description: primary key of the table
               tests:
                - unique
                - not_null
              


         