version: 2
sources:
   - name: raw
     schema: gz_raw_data #où se situe la table dans BQ
     description: greenwez raw data source
     tables:
         - name: sales
           identifier: raw_sales #Quel est le nom exacte de la table dans BQ
           description: sales of greewneez / we have one row per product_id found in each order_id
           loaded_at_field: "CAST(date_date AS TIMESTAMP)" # teste si la dernière commande a plus de 90 jours
           freshness: 
                warn_after:
                 count: 90
                 period: day  
                error_after:
                 count: 91
                 period: day

           columns:
             - name: "(orders_id || '-' || pdt_id)"#teste une concatenation de deux colonnes pour créer un PK qui n'existait pas en initial
               description: primary key of the table
               tests:
                 - unique
                 - not_null
             - name: date_date
               description: date de la commande sous format YYYY-MM-DD
             - name: orders_id
               description: numero a 6chiffres correspondant à la commande
             - name: products_id
               description: numero de référence du produit au catalogue
             - name: revenue
               description: chiffre d'affaire par commande et par numero de produit
             - name: quantity
               description: nombre de produit ayant la référence produit par commande
         - name: product
           identifier: raw_product
           description: purchase_price by products_id
           columns:
             - name: products_id
               description: primary key of the table
               tests:
                 - unique
                 - not_null
             - name: purchase_price
               description: prix du produit par référence produit     
         - name: ship
           identifier : raw_ship
           description : shipping cost by orders_id
           columns :
             - name: orders_id
               description: primary key of the table
               tests:
                - unique
                - not_null
             - name: shipping_fee
               description: taxe de livraison par commande(orders_id) 
             - name: logcost
               description: prix d'acheminement en format float par orders_id
             - name: ship_cost
               description: prix de livraison en format float par orders_id
         - name: facebook
           identifier : raw_gz_facebook
           description: campagne de pub sur facebook
           columns:
             - name: date_date
               description: primary key of the table
               tests:
                 - unique
                 - not_null
             - name: paid_source
               description:  indique la source de la campagne de pub cad facebook à chaque ligne
             - name: campaign_key
               description: numero donné à la campagne facebook le mme sur chaque ligne
             - name: camPGN_name
               description: nom de la campagne facebook
             - name: ads_cost
               description: sous format string le cout de la camapgne
             - name: impression
               description: nombre d'impression ou nombre daffichage de page
             - name: click
               description: nombre de click sur les pages
         - name: bing
           identifier : raw_gz_criteo
           description: campagne de pub sur bing
           columns:
             - name: date_date
               description: primary key of the table
               tests:
                 - unique
                 - not_null
             - name: paid_source
               description:  indique la source de la campagne de pub cad bing à chaque ligne
             - name: campaign_key
               description: numero donné à la campagne bing le mme sur chaque ligne
             - name: camPGN_name
               description: nom de la campagne bing
             - name: ads_cost
               description: sous format string le cout de la camapgne bing
             - name: impression
               description: nombre d'impression ou nombre daffichage de page
             - name: click
               description: nombre de click sur les pages
         - name: criteo
           identifier : raw_gz_criteotrue
           description: campagne de pub sur criteo
           columns:
             - name: date_date
               description: primary key of the table
               tests:
                 - unique
                 - not_null
             - name: paid_source
               description:  indique la source de la campagne de pub cad criteo à chaque ligne
             - name: campaign_key
               description: numero donné à la campagne criteo le mme sur chaque ligne
             - name: camPGN_name
               description: nom de la campagne criteo
             - name: ads_cost
               description: sous format string le cout de la camapgne
             - name: impression
               description: nombre d'impression ou nombre daffichage de page
             - name: click
               description: nombre de click sur les pages            
         - name: adwords
           identifier : raw_gz_adwords
           description: campagne de pub sur adwords
           columns:
             - name: date_date
               description: primary key of the table
               tests:
                 - unique
                 - not_null
             - name: paid_source
               description:  indique la source de la campagne de pub cad adwords à chaque ligne
             - name: campaign_key
               description: numero donné à la campagne adwords le mme sur chaque ligne
             - name: camPGN_name
               description: nom de la campagne adwords
             - name: ads_cost
               description: sous format string le cout de la camapgne adwords
             - name: impression
               description: nombre d'impression ou nombre daffichage de page adwords
             - name: click
               description: nombre de click sur les pages         


         